const STORE='seara_midia_v3';
let supabaseClient=null;
let realtimeChannel=null;
let remoteCult=null;
let remoteStatus='connecting';
const DEFAULT={theme:'light',cult:null,sequence:[],current:0,media:[],messages:[],log:[],standaloneMedia:[],settings:{church:'Assembleia de Deus Seara — Cabo'}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(STORE)||'{}'));
state.sequence=Array.isArray(state.sequence)?state.sequence:[]; state.messages=Array.isArray(state.messages)?state.messages:[]; state.media=Array.isArray(state.media)?state.media:[]; state.standaloneMedia=Array.isArray(state.standaloneMedia)?state.standaloneMedia:[];
const root=document.getElementById('app');
const modules=['Início','Modo Culto','Programação','Biblioteca de Mídia','Comunicação','Histórico'];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(STORE,JSON.stringify(state));}
function toast(msg){let el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function mediaSupabaseInit(){
  try{
    if(!window.supabase?.createClient) throw new Error('Biblioteca Supabase não carregada.');
    supabaseClient=window.supabase.createClient(SEARA_SUPABASE_CONFIG.url,SEARA_SUPABASE_CONFIG.publishableKey);
    return true;
  }catch(error){
    remoteStatus='error';
    console.error('[MÍDIA SEARA] Supabase indisponível',error);
    return false;
  }
}
function remoteCultToLocal(row){
  const tipo=row?.tipo?.nome||row?.tipo_slug||'Culto';
  const logo=row?.logo_path||row?.tipo?.logo_path||'';
  const sequence=Array.isArray(row?.liturgia)?row.liturgia.map((o,i)=>({
    id:o.id||crypto.randomUUID(),
    position:i+1,
    title:o.titulo||o.title||o.tipo||'Oportunidade',
    type:o.tipo||o.type||'Outra atividade',
    group:o.grupoId||o.grupo||'Sem grupo',
    note:[o.descricao,o.musicaSolicitada].filter(Boolean).join(' • '),
    status:o.status||'aguardando',
    remote:true
  })):[];
  return {
    id:row.id,
    name:row.titulo||tipo,
    type:tipo,
    date:row.data_inicio?new Date(row.data_inicio).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—',
    startedAt:row.data_inicio||new Date().toISOString(),
    note:row.observacoes||'',
    logo,
    remote:true,
    status:row.status,
    version:row.versao||1
  ,sequence};
}
function applyRemoteCult(row){
  remoteCult=remoteCultToLocal(row);
  state.cult=remoteCult;
  state.sequence=remoteCult.sequence||[];
  state.current=Math.max(0,Math.min(state.current,state.sequence.length-1));
  remoteStatus='connected';
  save();
}
async function fetchCultById(id){
  if(!supabaseClient||!id)return null;
  const {data,error}=await supabaseClient.from('seara_cultos').select('*, tipo:seara_culto_tipos(slug,nome,logo_path,cor_principal)').eq('id',id).single();
  if(error){console.error('[MÍDIA] Falha ao buscar culto',error);return null;}
  return data;
}
async function syncRemoteCultos(){
  if(!supabaseClient)return;
  const now=new Date().toISOString();
  const {data,error}=await supabaseClient.from('seara_cultos').select('*, tipo:seara_culto_tipos(slug,nome,logo_path,cor_principal)').order('data_inicio',{ascending:true}).limit(50);
  if(error){remoteStatus='error';console.error('[MÍDIA] Falha ao carregar cultos',error);return;}
  const candidates=(data||[]).filter(c=>!['encerrado','cancelado'].includes(c.status));
  const active=candidates.find(c=>c.status==='em_andamento')||candidates.find(c=>c.data_inicio&&c.data_inicio>=now)||candidates[0];
  if(active) applyRemoteCult(active);
  else remoteStatus='connected';
}
function subscribeRemote(){
  if(!supabaseClient)return;
  if(realtimeChannel)supabaseClient.removeChannel(realtimeChannel);
  realtimeChannel=supabaseClient.channel('seara-midia-realtime')
    .on('postgres_changes',{event:'INSERT',schema:'public',table:'seara_culto_eventos',filter:'destino_app=eq.seara-midia'},async payload=>{
      const row=payload.new||{};
      if(row.origem_app!=='seara-central')return;
      const culto=await fetchCultById(row.culto_id);
      if(culto){applyRemoteCult(culto);toast('Nova programação recebida do SEARA CENTRAL.');render('Modo Culto');}
    })
    .on('postgres_changes',{event:'UPDATE',schema:'public',table:'seara_cultos'},payload=>{
      const row=payload.new;
      if(remoteCult?.id===row.id){
        fetchCultById(row.id).then(c=>{if(c){applyRemoteCult(c);toast('Culto atualizado pelo SEARA CENTRAL.');render('Modo Culto');}});
      }
    })
    .subscribe(status=>{remoteStatus=status==='SUBSCRIBED'?'connected':status==='CHANNEL_ERROR'?'error':'connecting';});
}
async function initRemote(){
  if(!mediaSupabaseInit())return;
  await syncRemoteCultos();
  subscribeRemote();
}
function setTheme(dark){state.theme=dark?'dark':'light';document.documentElement.dataset.theme=dark?'dark':'';document.querySelector('meta[name="theme-color"]').setAttribute('content',dark?'#0c0c0d':'#ffffff');save();}
function layout(active){return `<div class="app"><aside class="sidebar" id="sidebar"><div class="brand"><img src="./assets/logo-midia.png" alt="Logo Mídia Seara"><div><strong>MÍDIA SEARA</strong><small>Operação visual do culto</small></div></div><nav class="nav">${modules.map(m=>`<button class="${m===active?'active':''}" data-nav="${esc(m)}">${esc(m)}</button>`).join('')}</nav><div class="sidebar-footer">Aplicativo operacional da Mídia.<br>O Modo Culto acompanha a sequência real recebida do SEARA CENTRAL e permite ajustes operacionais durante a celebração.</div></aside><main class="main"><header class="topbar"><div class="top-title"><button class="mobile-toggle" id="toggle">☰</button><div><h1>MÍDIA SEARA</h1><span>Assembleia de Deus • Cabo</span></div></div><div class="top-actions"><span class="badge ${state.cult?'live':'warn'}">${state.cult?'CULTO RECEBIDO':'SEM CULTO'}</span><span class="badge ${remoteStatus==='connected'?'live':remoteStatus==='error'?'warn':''}">${remoteStatus==='connected'?'CENTRAL CONECTADO':remoteStatus==='error'?'CENTRAL OFFLINE':'CONECTANDO...'}</span><button class="btn small" id="theme">${state.theme==='dark'?'☀ Claro':'☾ Escuro'}</button></div></header><section class="content" id="content"></section></main></div><div id="toast" class="toast"></div>`}
function render(active='Início'){root.innerHTML=layout(active);document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{show(b.dataset.nav);document.getElementById('sidebar').classList.remove('open')});document.getElementById('toggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('theme').onclick=()=>{setTheme(state.theme!=='dark');render(active)};setTheme(state.theme==='dark');show(active)}
function show(m){if(m==='Início')home();else if(m==='Modo Culto')cultMode();else if(m==='Programação')program();else if(m==='Biblioteca de Mídia')mediaLibrary();else if(m==='Comunicação')chat();else historyPage();}
function home(){const c=document.getElementById('content');c.innerHTML=`<div class="hero"><div class="hero-copy"><div class="badge blue">MÍDIA • OPERAÇÃO DO CULTO</div><h2>O centro visual da celebração.</h2><p>A Mídia acompanha a sequência real do culto, exibe conteúdos, recebe alterações do pastor e pode inserir recursos visuais sem quebrar a liturgia principal.</p><div class="controls"><button class="btn primary" id="start">${state.cult?'Abrir Modo Culto':'Iniciar culto'}</button><button class="btn" id="program">Abrir programação</button></div></div><img class="logo-hero" src="./assets/logo-midia.png" alt="Mídia Seara"></div><div class="grid"><div class="card"><h3>Culto atual</h3><div class="metric">${state.cult?esc(state.cult.name):'—'}</div><div class="muted">${state.cult?esc(state.cult.date):'Nenhum culto em andamento'}</div></div><div class="card"><h3>Agora</h3><div class="metric">${currentItem()?.position??'—'}</div><div class="muted">${currentItem()?.title||'Nenhuma oportunidade'}</div></div><div class="card"><h3>Sequência</h3><div class="metric">${state.sequence.length}</div><div class="muted">itens na programação atual</div></div><div class="card"><h3>Comunicação</h3><div class="metric">${state.messages.length}</div><div class="muted">mensagens registradas</div></div></div><div class="section"><div class="section-title"><h3>Responsabilidade da Mídia</h3></div><div class="card"><p class="muted">Durante o culto, a Mídia acompanha <strong>AGORA / PRÓXIMO / DEPOIS</strong>, exibe recursos visuais, registra alterações solicitadas pelo pastor e mantém a sequência operacional. Conteúdos adicionais podem ser colocados em uma fila auxiliar sem alterar a raiz da liturgia.</p></div></div>`;document.getElementById('start').onclick=()=>{if(!state.cult)openCult();else render('Modo Culto')};document.getElementById('program').onclick=()=>render('Programação')}
function openCult(){modal(`<h3>Iniciar culto</h3><form id="cultForm" class="form"><div class="form-grid"><div class="field"><label>Nome do culto</label><input name="name" placeholder="Ex.: Culto de Adoração" required></div><div class="field"><label>Data</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div></div><div class="field"><label>Observação inicial</label><textarea name="note" placeholder="Informação para a operação da Mídia"></textarea></div><div><button type="button" class="btn" id="mc">Cancelar</button> <button class="btn primary">Iniciar culto</button></div></form>`);document.getElementById('mc').onclick=closeModal;document.getElementById('cultForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.cult={id:crypto.randomUUID(),name:f.get('name'),date:f.get('date'),note:f.get('note'),startedAt:new Date().toISOString()};state.current=0;save();closeModal();render('Modo Culto');toast('Culto iniciado.')}}
function currentItem(){return state.sequence[state.current]||null}
function cultMode(){const c=document.getElementById('content');if(!state.cult){c.innerHTML=`<div class="empty"><h2>Nenhum culto em andamento.</h2><p>Inicie um culto para abrir o modo operacional da Mídia.</p><button class="btn primary" id="go">Iniciar culto</button></div>`;document.getElementById('go').onclick=openCult;return}const now=currentItem(),next=state.sequence[state.current+1],after=state.sequence.slice(state.current+2,state.current+5);c.innerHTML=`<div class="cult-header"><div><h2>${esc(state.cult.name)}</h2><p>${esc(state.cult.date)} • iniciado ${new Date(state.cult.startedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</p></div><div class="toolbar-actions"><button class="btn" id="rootEdit">Editar liturgia</button><button class="btn blue" id="addNow">Inserir na sequência</button><button class="btn" id="extra">Mídia auxiliar</button><button class="btn danger" id="end">Encerrar</button></div></div><div class="sequence"><div class="now-card"><div class="now-label">AGORA</div><div class="now-title">${now?esc(now.title):'Nenhuma oportunidade'}</div><div class="now-meta">${now?`${esc(now.type)} • ${esc(now.group||'Sem grupo')} ${now.note?`• ${esc(now.note)}`:''}`:'Adicione uma oportunidade à sequência.'}</div><div class="controls"><button class="btn" id="prev" ${state.current<=0?'disabled':''}>← Voltar</button><button class="btn primary" id="next" ${state.current>=state.sequence.length-1?'disabled':''}>Avançar →</button><button class="btn" id="done">Concluir atual</button></div></div><div><div class="section-title"><h3>PRÓXIMO</h3></div>${next?seqCard(next,state.current+1):`<div class="empty">Não há próxima oportunidade.</div>`}</div><div><div class="section-title"><h3>DEPOIS</h3></div><div class="sequence-list">${after.length?after.map((x,i)=>seqCard(x,state.current+i+2)).join(''):`<div class="empty">Sem itens seguintes.</div>`}</div></div></div><div class="section"><div class="section-title"><h3>Sequência atual</h3><span class="muted">${state.sequence.length} oportunidades</span></div><div class="card"><div class="sequence-list">${state.sequence.length?state.sequence.map((x,i)=>seqCard(x,i)).join(''):`<div class="empty">A sequência está vazia.</div>`}</div></div></div>`;document.getElementById('prev').onclick=()=>{state.current=Math.max(0,state.current-1);save();render('Modo Culto')};document.getElementById('next').onclick=()=>{state.current=Math.min(state.sequence.length-1,state.current+1);save();render('Modo Culto')};document.getElementById('done').onclick=()=>{if(currentItem()){state.log.push({...currentItem(),status:'CONCLUÍDA',at:new Date().toISOString()});state.current=Math.min(state.sequence.length-1,state.current+1);save();render('Modo Culto');toast('Oportunidade concluída.')}};document.getElementById('addNow').onclick=()=>opportunityForm();document.getElementById('rootEdit').onclick=()=>program(true);document.getElementById('extra').onclick=()=>mediaOverlay();document.getElementById('end').onclick=endCult}
function seqCard(x,i){return `<div class="seq-item ${i===state.current?'current':''}"><div><div class="seq-number">${String(i+1).padStart(2,'0')}</div><div class="seq-title">${esc(x.title)}</div><div class="seq-sub">${esc(x.type)} • ${esc(x.group||'Sem grupo')}${x.note?' • '+esc(x.note):''}</div></div><span class="badge ${i<state.current?'live':''}">${i<state.current?'CONCLUÍDA':i===state.current?'AGORA':'AGUARDANDO'}</span></div>`}
function opportunityForm(){modal(`<h3>Inserir oportunidade</h3><form id="opForm" class="form"><div class="form-grid three"><div class="field"><label>Nome da oportunidade</label><input name="title" required placeholder="Ex.: Aviso especial"></div><div class="field"><label>Tipo</label><select name="type"><option>Saudação</option><option>Cantar um louvor</option><option>Declamar poesia</option><option>Contar testemunho</option><option>Oração</option><option>Leitura</option><option>Harpa Cristã</option><option>Aviso</option><option>Pregação</option><option>Convite</option><option>Participação especial</option><option>Outro</option></select></div><div class="field"><label>Grupo / origem</label><input name="group" placeholder="Ex.: JADS"></div></div><div class="field"><label>Observação para a operação</label><textarea name="note" placeholder="Orientação para a Mídia"></textarea></div><div><button type="button" class="btn" id="mc">Cancelar</button> <button class="btn primary">Adicionar agora</button></div></form>`);document.getElementById('mc').onclick=closeModal;document.getElementById('opForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const item={id:crypto.randomUUID(),title:f.get('title'),type:f.get('type'),group:f.get('group'),note:f.get('note'),createdAt:new Date().toISOString()};state.sequence.splice(state.current+1,0,item);save();closeModal();render('Modo Culto');toast('Oportunidade inserida na sequência.')}}
function program(fromMode=false){const c=document.getElementById('content');c.innerHTML=`<div class="toolbar"><div><h2>Programação / Liturgia</h2><div class="muted">A raiz da liturgia pode ser ajustada durante o culto quando autorizado.</div></div><div class="toolbar-actions"><button class="btn primary" id="add">Adicionar oportunidade</button>${state.cult?'<button class="btn" id="back">Voltar ao Modo Culto</button>':''}</div></div>${state.cult?`<div class="card" style="margin-bottom:14px"><strong>${esc(state.cult.name)}</strong><div class="muted">Ajustes nesta tela alteram a sequência operacional do culto atual.</div></div>`:''}<div class="card"><div class="sequence-list">${state.sequence.length?state.sequence.map((x,i)=>`<div class="seq-item"><div><div class="seq-number">${String(i+1).padStart(2,'0')}</div><div class="seq-title">${esc(x.title)}</div><div class="seq-sub">${esc(x.type)} • ${esc(x.group||'Sem grupo')} ${x.note?'• '+esc(x.note):''}</div></div><div class="toolbar-actions"><button class="btn small" data-up="${i}" ${i===0?'disabled':''}>↑</button><button class="btn small" data-down="${i}" ${i===state.sequence.length-1?'disabled':''}>↓</button><button class="btn small danger" data-del="${i}">Excluir</button></div></div>`).join(''):`<div class="empty">Nenhuma oportunidade cadastrada na sequência.</div>`}</div></div>`;document.getElementById('add').onclick=opportunityForm;document.getElementById('back')?.addEventListener('click',()=>render('Modo Culto'));c.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(+b.dataset.up,-1));c.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(+b.dataset.down,1));c.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.sequence.splice(+b.dataset.del,1);state.current=Math.min(state.current,Math.max(0,state.sequence.length-1));save();program()})}
function move(i,d){const j=i+d;if(j<0||j>=state.sequence.length)return;[state.sequence[i],state.sequence[j]]=[state.sequence[j],state.sequence[i]];save();program()}
function mediaLibrary(){const c=document.getElementById('content');c.innerHTML=`<div class="toolbar"><div><h2>Biblioteca de Mídia</h2><div class="muted">Recursos visuais e arquivos que podem ser exibidos durante o culto.</div></div><div class="toolbar-actions"><button class="btn primary" id="upload">Adicionar arquivo</button><button class="btn" id="url">Adicionar por URL</button></div></div><div class="card"><input id="file" type="file" accept="audio/*,video/*,image/*" hidden><div class="empty">${state.media.length?`${state.media.length} recurso(s) cadastrado(s). Selecione um recurso para reprodução.`:'Nenhuma mídia cadastrada.'}</div></div><div class="section"><div class="section-title"><h3>Recursos cadastrados</h3></div><div class="grid">${state.media.map((m,i)=>`<div class="card"><span class="badge">${esc(m.kind)}</span><h3>${esc(m.name)}</h3><div class="muted">${esc(m.source||'Arquivo local')}</div><div class="controls"><button class="btn small primary" data-play="${i}">Reproduzir</button><button class="btn small danger" data-md="${i}">Excluir</button></div></div>`).join('')}</div></div>`;document.getElementById('upload').onclick=()=>document.getElementById('file').click();document.getElementById('file').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{state.media.push({id:crypto.randomUUID(),name:f.name,kind:f.type.startsWith('video')?'VÍDEO':f.type.startsWith('audio')?'ÁUDIO':'IMAGEM',source:'Arquivo local',data:reader.result});save();mediaLibrary();toast('Arquivo adicionado.');};reader.readAsDataURL(f)};document.getElementById('url').onclick=()=>{modal(`<h3>Adicionar mídia por URL</h3><form id="urlForm" class="form"><div class="field"><label>Nome</label><input name="name" required></div><div class="field"><label>URL direta do arquivo</label><input name="url" type="url" placeholder="https://..." required></div><div><button type="button" class="btn" id="mc">Cancelar</button> <button class="btn primary">Adicionar</button></div></form>`);document.getElementById('mc').onclick=closeModal;document.getElementById('urlForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const url=f.get('url');state.media.push({id:crypto.randomUUID(),name:f.get('name'),kind:/\.(mp4|webm|mov)(\?|$)/i.test(url)?'VÍDEO':'ÁUDIO',source:'URL',data:url});save();closeModal();mediaLibrary()}};c.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>player(state.media[+b.dataset.play]));c.querySelectorAll('[data-md]').forEach(b=>b.onclick=()=>{state.media.splice(+b.dataset.md,1);save();mediaLibrary()})}
function player(m){modal(`<div class="modal-head"><h3>${esc(m.name)}</h3><button class="btn small" id="x">Fechar</button></div><div class="player"><div class="player-stage" id="stage"></div></div>`);document.getElementById('x').onclick=closeModal;const s=document.getElementById('stage');if(m.kind==='VÍDEO'){s.innerHTML=`<video src="${esc(m.data)}" controls autoplay playsinline></video>`}else if(m.kind==='ÁUDIO'){s.innerHTML=`<audio src="${esc(m.data)}" controls autoplay></audio>`}else{s.innerHTML=`<img src="${esc(m.data)}" alt="${esc(m.name)}" style="max-width:100%;max-height:55vh;object-fit:contain">`}}
function mediaOverlay(){const extras=state.standaloneMedia;modal(`<h3>Mídia auxiliar</h3><p class="muted">A mídia auxiliar é exibida sem alterar a sequência da liturgia. Ela existe para uma necessidade operacional durante o culto.</p><div class="section"><div class="sequence-list">${extras.length?extras.map((m,i)=>`<div class="seq-item"><div><strong>${esc(m.name)}</strong><div class="seq-sub">${esc(m.kind)}</div></div><button class="btn small primary" data-aux="${i}">Abrir</button></div>`).join(''):'<div class="empty">Nenhuma mídia auxiliar cadastrada.</div>'}</div></div><div class="controls"><button class="btn" id="close">Fechar</button><button class="btn primary" id="addAux">Adicionar recurso</button></div>`);document.getElementById('close').onclick=closeModal;document.getElementById('addAux').onclick=()=>{closeModal();mediaLibrary()};document.querySelectorAll('[data-aux]').forEach(b=>b.onclick=()=>player(extras[+b.dataset.aux]))}
function chat(){const c=document.getElementById('content');const msgs=state.messages;c.innerHTML=`<div class="toolbar"><div><h2>Comunicação com o Pastor</h2><div class="muted">Canal operacional para alterações, confirmações e observações durante o culto.</div></div><span class="badge blue">FUTURA INTEGRAÇÃO</span></div><div class="chat"><div class="chat-list"><h3>Conversas</h3><button class="chat-room active"><strong>Pastor / Direção</strong><small style="display:block;color:var(--muted);margin-top:3px">Alterações do culto</small></button><button class="chat-room"><strong>SEARA CENTRAL</strong><small style="display:block;color:var(--muted);margin-top:3px">Programação</small></button></div><div class="chat-main"><div class="chat-head"><strong>Pastor / Direção</strong><div class="muted">Mensagens ficam vinculadas à operação nesta etapa.</div></div><div class="messages">${msgs.length?msgs.map(m=>`<div class="msg ${m.mine?'mine':''}">${esc(m.text)}<small>${m.mine?'Mídia':'Pastor / Direção'} • ${new Date(m.at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):`<div class="empty">Nenhuma mensagem ainda.<br>O canal será conectado ao SEARA CENTRAL na fase de integração.</div>`}</div><form class="chat-compose" id="chatForm"><input name="text" placeholder="Enviar observação ao pastor..." required><button class="btn primary">Enviar</button></form></div></div>`;document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.messages.push({id:crypto.randomUUID(),text:f.get('text'),mine:true,at:new Date().toISOString()});save();chat();toast('Mensagem registrada localmente.')}}
function historyPage(){const c=document.getElementById('content');c.innerHTML=`<div class="toolbar"><div><h2>Histórico operacional</h2><div class="muted">Registro das ações feitas pela Mídia nesta versão.</div></div></div>${state.log.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Horário</th><th>Oportunidade</th><th>Tipo</th><th>Grupo</th><th>Status</th></tr></thead><tbody>${state.log.slice().reverse().map(x=>`<tr><td>${new Date(x.at).toLocaleString('pt-BR')}</td><td><strong>${esc(x.title)}</strong></td><td>${esc(x.type)}</td><td>${esc(x.group||'—')}</td><td><span class="badge live">${esc(x.status)}</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma ação registrada ainda.</div>'}`}
function endCult(){if(!confirm('Encerrar o culto? A sequência e o histórico local serão preservados.'))return;if(state.cult){state.log.push({title:`Culto encerrado: ${state.cult.name}`,type:'CULTO',group:'Mídia',status:'ENCERRADO',at:new Date().toISOString()});}state.cult=null;state.sequence=[];state.current=0;save();render('Início');toast('Culto encerrado.')}
function modal(body){closeModal();const o=document.createElement('div');o.className='overlay';o.id='overlay';o.innerHTML=`<div class="modal">${body}</div>`;document.body.appendChild(o)}
function closeModal(){document.getElementById('overlay')?.remove()}
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(state.cult&&document.getElementById('content')&&document.querySelector('.now-card')){if(e.key==='ArrowRight'){state.current=Math.min(state.sequence.length-1,state.current+1);save();render('Modo Culto')}if(e.key==='ArrowLeft'){state.current=Math.max(0,state.current-1);save();render('Modo Culto')}}});
setTheme(state.theme==='dark');render('Início');
initRemote().then(()=>{render('Início');}).catch(error=>{console.error(error);remoteStatus='error';render('Início');});
